# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import event_pb2 as event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\x12\x07loom.v1\x1a\x0b\x65vent.proto\"\xd7\x01\n\nPluginMeta\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12!\n\x04type\x18\x04 \x01(\x0e\x32\x13.loom.v1.PluginType\x12\x14\n\x0c\x63\x61pabilities\x18\x05 \x03(\t\x12/\n\x06\x63onfig\x18\x06 \x03(\x0b\x32\x1f.loom.v1.PluginMeta.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"o\n\x0ePluginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x12%\n\routput_events\x18\x04 \x03(\x0b\x32\x0e.loom.v1.Event\"\x95\x01\n\x0cHealthStatus\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x33\n\x07metrics\x18\x03 \x03(\x0b\x32\".loom.v1.HealthStatus.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\rHealthRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"3\n\x0fShutdownRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08*j\n\nPluginType\x12\x1c\n\x18PLUGIN_FEATURE_EXTRACTOR\x10\x00\x12\x18\n\x14PLUGIN_MODEL_BACKEND\x10\x01\x12\x0f\n\x0bPLUGIN_TOOL\x10\x02\x12\x13\n\x0fPLUGIN_ACTUATOR\x10\x03\x32\xee\x01\n\x06Plugin\x12\x34\n\x04Init\x12\x13.loom.v1.PluginMeta\x1a\x17.loom.v1.PluginResponse\x12\x36\n\x0bHandleEvent\x12\x0e.loom.v1.Event\x1a\x17.loom.v1.PluginResponse\x12\x37\n\x06Health\x12\x16.loom.v1.HealthRequest\x1a\x15.loom.v1.HealthStatus\x12=\n\x08Shutdown\x12\x18.loom.v1.ShutdownRequest\x1a\x17.loom.v1.PluginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLUGINMETA_CONFIGENTRY']._loaded_options = None
  _globals['_PLUGINMETA_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHSTATUS_METRICSENTRY']._loaded_options = None
  _globals['_HEALTHSTATUS_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_PLUGINTYPE']._serialized_start=610
  _globals['_PLUGINTYPE']._serialized_end=716
  _globals['_PLUGINMETA']._serialized_start=39
  _globals['_PLUGINMETA']._serialized_end=254
  _globals['_PLUGINMETA_CONFIGENTRY']._serialized_start=209
  _globals['_PLUGINMETA_CONFIGENTRY']._serialized_end=254
  _globals['_PLUGINRESPONSE']._serialized_start=256
  _globals['_PLUGINRESPONSE']._serialized_end=367
  _globals['_HEALTHSTATUS']._serialized_start=370
  _globals['_HEALTHSTATUS']._serialized_end=519
  _globals['_HEALTHSTATUS_METRICSENTRY']._serialized_start=473
  _globals['_HEALTHSTATUS_METRICSENTRY']._serialized_end=519
  _globals['_HEALTHREQUEST']._serialized_start=521
  _globals['_HEALTHREQUEST']._serialized_end=555
  _globals['_SHUTDOWNREQUEST']._serialized_start=557
  _globals['_SHUTDOWNREQUEST']._serialized_end=608
  _globals['_PLUGIN']._serialized_start=719
  _globals['_PLUGIN']._serialized_end=957
# @@protoc_insertion_point(module_scope)